### ISSUE TITLE
Css Inliner + Markup - Width, Margin & Spacing Issue for Outlook 

### ISSUE THREAD

**Issue by priyankpardiwala** [adobe/aem-core-email-components#146]
This issue is closely related to Issue #118 and it is related to how Page component, layout container component HTML look like. 

Please see the screenshot below. I created an email template, where the root container is 890px and is centered aligned. I gave additional 20px padding to the root container. 

![image](https://user-images.githubusercontent.com/102314745/171268326-f28c164d-689e-443e-aa45-e7e71c9e93f7.png)

Here's how the CSS for "root" class looks like. 

![image](https://user-images.githubusercontent.com/102314745/171268510-56c99e01-77e8-4657-bf64-e6087603b003.png)

But when we deliver the actual email through campaign, outlook ignores the  width, padding and margin attributes even though they are inlined as style attribute on the <div> 

Here's a screenshot of how the actual email looks like- 
![image](https://user-images.githubusercontent.com/102314745/171268767-89e854e6-e89f-4916-8d11-e8077553148a.png)

Expected result is for the actual email to look exactly like email page when viewed in the browser.

**Comment by edoardo-goracci** [comment]
Hi @priyankpardiwala,
sorry for the late reply. I think adding style to the root DIV element is not the best way to style this page (since we didn't really test width and padding styles on DIVs during our Litmus testing); I think you can achieve the same result by adding these CSS selectors to the top-level **<table class="layout" role="presentation">** element (which is accessible with **div.root.responsivegrid > div > div.container.responsivegrid.aem-GridColumn.aem-GridColumn--default--12 > center > table** selector). You can also simplify the HTML structure of the page by adding the "**responsivegrid**" class to the wrapper DIV remover OSGI configuration: by doing so, you can access the table element simply with **center > table** selector.

**Comment by edoardo-goracci** [comment]
After discussing this with @gabrielwalt and @priyankpardiwala at last Friday's meeting, we decided to create https://github.com/adobe/aem-core-email-components/issues/177 to fix this issue.
